Use New Routing V1
ipfs-shipyard/someguy pull request #17
Opened 2023-10-10 11:19 UTC by hacdias

2023-10-11 09:12 UTC, aschmahmann requested changes
Looks good, thanks 🙏. Haven't gotten a chance to run it and push on it though. Had some small comments and suggestions.

2023-10-11 09:12 UTC, aschmahmann commented on server.go
> +	log.Printf("Delegated Routing API on http://127.0.0.1:%d/routing/v1", port)
Might be fine, but also a little confusing since routing/v1 is on 127.0.0.1 and all other interfaces too.

2023-10-11 18:40 UTC, lidel commented on main.go
> +						Name:  "content-endpoints",
nit: match endpoint name from /routing/v1 like we do for other two
```suggestion
						Name:  "provider-endpoints",
```

2023-10-12 13:52 UTC, hacdias commented on go.mod
> +	github.com/ipfs/boxo v0.13.2-0.20231009073559-45c797e0ccea
Yeah, the reason I'm not using latest is because `client.Client` is not exposed 🥲

2023-10-16 14:31 UTC, aschmahmann approved these changes
LGTM

2023-10-16 15:01 UTC, hacdias commented
Merging for now. Following up on #18 once Boxo is released.

2023-10-16 15:02 UTC, merged